'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { KeyRound, Loader2, LogOut, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  beginMfaEnrolment,
  changePassword,
  confirmMfaEnrolment,
  disableMfa,
  revokeOtherSessions,
} from '@/server/security'

/**
 * The enrolment QR, rendered from SVG the server produced.
 *
 * No image host is involved: a public QR service would have received the
 * client's TOTP secret in a query string, which would defeat the point of
 * the factor. The markup is generated by our own encoder
 * (src/domain/security/qr.ts) and is inert — no scripts, no links.
 */
function QrImage({ svg }: { svg: string }) {
  return (
    <div
      className="rounded-md border bg-white p-2"
      role="img"
      aria-label="QR code for your authenticator app"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  )
}

export function MfaEnrolment({ enabled }: { enabled: boolean }) {
  const router = useRouter()
  const [open, setOpen] = useState(false)
  const [pending, startTransition] = useTransition()
  const [setup, setSetup] = useState<{ secret: string; qrSvg: string } | null>(null)
  const [token, setToken] = useState('')
  const [recoveryCodes, setRecoveryCodes] = useState<string[] | null>(null)

  if (enabled) {
    return (
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger render={<Button variant="outline">Turn off two-factor</Button>} />
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Turn off two-factor authentication?</DialogTitle>
            <DialogDescription>
              Enter a current code from your authenticator app. Turning this off without one is not
              possible — a stolen session alone must not be enough.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-1.5">
            <Label htmlFor="disable-token">Authentication code</Label>
            <Input
              id="disable-token"
              inputMode="numeric"
              maxLength={6}
              value={token}
              onChange={(event) => setToken(event.target.value)}
              placeholder="000000"
            />
          </div>
          <DialogFooter>
            <DialogClose render={<Button variant="ghost">Cancel</Button>} />
            <Button
              variant="destructive"
              disabled={pending || token.length !== 6}
              onClick={() =>
                startTransition(async () => {
                  const result = await disableMfa({ token })
                  if (!result.ok) {
                    toast.error(result.error)
                    return
                  }
                  toast.success('Two-factor authentication turned off.')
                  setOpen(false)
                  setToken('')
                  router.refresh()
                })
              }
            >
              {pending ? <Loader2 className="mr-1 size-3.5 animate-spin" /> : null}
              Turn off
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    )
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        setOpen(next)
        if (!next) {
          setSetup(null)
          setToken('')
          setRecoveryCodes(null)
        }
      }}
    >
      <DialogTrigger
        render={
          <Button
            onClick={() =>
              startTransition(async () => {
                const result = await beginMfaEnrolment()
                if (!result.ok) {
                  toast.error(result.error)
                  return
                }
                setSetup(result.value ?? null)
              })
            }
          >
            <ShieldCheck className="mr-1 size-4" aria-hidden="true" />
            Enable two-factor
          </Button>
        }
      />
      <DialogContent>
        {recoveryCodes ? (
          <>
            <DialogHeader>
              <DialogTitle>Two-factor authentication is on</DialogTitle>
              <DialogDescription>
                Save these recovery codes somewhere safe. Each one works once, if you lose your
                phone. They are shown now and never again.
              </DialogDescription>
            </DialogHeader>
            <ul className="bg-muted grid grid-cols-2 gap-1 rounded-md p-3 font-mono text-sm">
              {recoveryCodes.map((code) => (
                <li key={code}>{code}</li>
              ))}
            </ul>
            <DialogFooter>
              <DialogClose render={<Button>I have saved them</Button>} />
            </DialogFooter>
          </>
        ) : setup ? (
          <>
            <DialogHeader>
              <DialogTitle>Scan this with your authenticator app</DialogTitle>
              <DialogDescription>
                Google Authenticator, 1Password, Authy — any TOTP app works.
              </DialogDescription>
            </DialogHeader>
            <div className="flex flex-col items-center gap-3">
              <QrImage svg={setup.qrSvg} />
              <p className="text-muted-foreground text-center text-xs">
                Can&apos;t scan? Enter this key manually:
                <br />
                <code className="font-mono text-sm break-all">{setup.secret}</code>
              </p>
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="confirm-token">Enter the 6-digit code to confirm</Label>
              <Input
                id="confirm-token"
                inputMode="numeric"
                maxLength={6}
                value={token}
                onChange={(event) => setToken(event.target.value)}
                placeholder="000000"
              />
            </div>
            <DialogFooter>
              <DialogClose render={<Button variant="ghost">Cancel</Button>} />
              <Button
                disabled={pending || token.length !== 6}
                onClick={() =>
                  startTransition(async () => {
                    const result = await confirmMfaEnrolment({ token })
                    if (!result.ok) {
                      toast.error(result.error)
                      return
                    }
                    setRecoveryCodes(result.value?.recoveryCodes ?? [])
                    router.refresh()
                  })
                }
              >
                {pending ? <Loader2 className="mr-1 size-3.5 animate-spin" /> : null}
                Confirm
              </Button>
            </DialogFooter>
          </>
        ) : (
          <div className="flex items-center justify-center py-8">
            <Loader2 className="size-5 animate-spin" />
          </div>
        )}
      </DialogContent>
    </Dialog>
  )
}

export function ChangePasswordDialog() {
  const router = useRouter()
  const [open, setOpen] = useState(false)
  const [pending, startTransition] = useTransition()
  const [form, setForm] = useState({ currentPassword: '', newPassword: '', confirmPassword: '' })

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger
        render={
          <Button variant="outline">
            <KeyRound className="mr-1 size-4" aria-hidden="true" />
            Change password
          </Button>
        }
      />
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Change your password</DialogTitle>
          <DialogDescription>
            Your current password is re-checked, not assumed from the session.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="current-password">Current password</Label>
            <Input
              id="current-password"
              type="password"
              value={form.currentPassword}
              onChange={(event) => setForm({ ...form, currentPassword: event.target.value })}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="new-password">New password</Label>
            <Input
              id="new-password"
              type="password"
              value={form.newPassword}
              onChange={(event) => setForm({ ...form, newPassword: event.target.value })}
            />
            <p className="text-muted-foreground text-xs">
              At least 10 characters, with an uppercase letter, a lowercase letter and a number.
            </p>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="confirm-password">Confirm new password</Label>
            <Input
              id="confirm-password"
              type="password"
              value={form.confirmPassword}
              onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })}
            />
          </div>
        </div>

        <DialogFooter>
          <DialogClose render={<Button variant="ghost">Cancel</Button>} />
          <Button
            disabled={pending || !form.currentPassword || form.newPassword.length < 10}
            onClick={() =>
              startTransition(async () => {
                const result = await changePassword(form)
                if (!result.ok) {
                  toast.error(result.error)
                  return
                }
                toast.success('Password changed.')
                setOpen(false)
                setForm({ currentPassword: '', newPassword: '', confirmPassword: '' })
                router.refresh()
              })
            }
          >
            {pending ? <Loader2 className="mr-1 size-3.5 animate-spin" /> : null}
            Change password
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

export function RevokeSessionsButton() {
  const router = useRouter()
  const [pending, startTransition] = useTransition()

  return (
    <Button
      variant="outline"
      disabled={pending}
      onClick={() =>
        startTransition(async () => {
          const result = await revokeOtherSessions()
          if (!result.ok) {
            toast.error(result.error)
            return
          }
          toast.success('Signed out everywhere else.')
          router.refresh()
        })
      }
    >
      {pending ? (
        <Loader2 className="mr-1 size-4 animate-spin" />
      ) : (
        <LogOut className="mr-1 size-4" aria-hidden="true" />
      )}
      Sign out other devices
    </Button>
  )
}
